Repository elastic/elastic-stack-testing, pull requests merged in 2020-05, with the labels that each got.

#551 Add more tests
  ci/kibana/group_defs.sh
Labels: :CI:Jobs

#554 [7.x] Update settings (#553)
  ci/cloud/product/settings/kibana.yml
Labels: backport

#555 [7.8] Update settings (#553)
  ci/cloud/product/settings/kibana.yml
Labels: backport

#557 [7.x] Update ece and eck settings (#556)
  ci/cloud/ece/ecePlan.json
  ci/cloud/eck/kbn-spec.yml
Labels: backport

#558 [7.8] Update ece and eck settings (#556)
  ci/cloud/ece/ecePlan.json
  ci/cloud/eck/kbn-spec.yml
Labels: backport

#567 Print commit info for elasticsearch, kibana and test code
  ci/cloud/common/build.gradle
  ci/cloud/ece/build.gradle
  ci/cloud/eck/build.gradle
  ci/cloud/saas/build.gradle
Labels: :Cloud Framework

#568 [7.x] Print commit info for elasticsearch, kibana and test code (#567)
  ci/cloud/common/build.gradle
  ci/cloud/ece/build.gradle
  ci/cloud/eck/build.gradle
  ci/cloud/saas/build.gradle
Labels: backport

#569 [7.8] Print commit info for elasticsearch, kibana and test code (#567)
  ci/cloud/common/build.gradle
  ci/cloud/ece/build.gradle
  ci/cloud/eck/build.gradle
  ci/cloud/saas/build.gradle
Labels: backport

#570 [7.7] Print commit info for elasticsearch, kibana and test code (#567)
  ci/cloud/common/build.gradle
  ci/cloud/ece/build.gradle
  ci/cloud/eck/build.gradle
  ci/cloud/saas/build.gradle
Labels: backport

#571 [7.6] Print commit info for elasticsearch, kibana and test code (#567)
  ci/cloud/common/build.gradle
  ci/cloud/ece/build.gradle
  ci/cloud/eck/build.gradle
  ci/cloud/saas/build.gradle
Labels: backport

#572 [6.8] Print commit info for elasticsearch, kibana and test code (#567)
  ci/cloud/common/build.gradle
  ci/cloud/ece/build.gradle
  ci/cloud/eck/build.gradle
  ci/cloud/saas/build.gradle
Labels: backport

#574 [7.x] Fix kbn url, spaces, add print (#573)
  ci/cloud/common/build.gradle
  ci/cloud/ece/build.gradle
  ci/cloud/eck/build.gradle
  ci/cloud/saas/build.gradle
Labels: backport

#575 [7.8] Fix kbn url, spaces, add print (#573)
  ci/cloud/common/build.gradle
  ci/cloud/ece/build.gradle
  ci/cloud/eck/build.gradle
  ci/cloud/saas/build.gradle
Labels: backport

#576 [7.7] Fix kbn url, spaces, add print (#573)
  ci/cloud/common/build.gradle
  ci/cloud/ece/build.gradle
  ci/cloud/eck/build.gradle
  ci/cloud/saas/build.gradle
Labels: backport

#577 [6.8] Fix kbn url, spaces, add print (#573)
  ci/cloud/common/build.gradle
  ci/cloud/ece/build.gradle
  ci/cloud/eck/build.gradle
  ci/cloud/saas/build.gradle
Labels: backport

#578 [7.x] Replace references to "internal" with "legacy" (#549)
  playbooks/monitoring/README.md
  playbooks/monitoring/beat/docs_compare.py
  playbooks/monitoring/beat/docs_parity.yml
  playbooks/monitoring/common/docs_compare_util.py
  playbooks/monitoring/elasticsearch/docs_compare.py
  playbooks/monitoring/elasticsearch/docs_parity.yml
  playbooks/monitoring/kibana/docs_compare.py
  playbooks/monitoring/kibana/docs_parity.yml
  playbooks/monitoring/logstash/docs_compare.py
  playbooks/monitoring/logstash/docs_parity.yml
Labels: backport

#583 [7.x] Update settings (#582)
  ci/cloud/ece/ecePlan.json
  ci/cloud/eck/kbn-spec.yml
  ci/cloud/product/settings/kibana.yml
  ci/kibana/group_defs.sh
Labels: backport

#587 [7.x] Use python3 instead of python3.6 (#586)
  scripts/shell/lib/build_funcs.sh
Labels: backport

#588 [7.8] Use python3 instead of python3.6 (#586)
  scripts/shell/lib/build_funcs.sh
Labels: backport

#589 [7.7] Use python3 instead of python3.6 (#586)
  scripts/shell/lib/build_funcs.sh
Labels: backport

#590 [6.8] Use python3 instead of python3.6 (#586)
  scripts/shell/lib/build_funcs.sh
Labels: backport

#592 [7.x] Update machine learning folder name (3c97d24f)
  ci/kibana/group_defs.sh
Labels: backport

#593 [7.x] Fix print info, certifcate issue (#591)
  ci/cloud/ece/build.gradle
  ci/cloud/eck/.project
  ci/cloud/eck/.settings/org.eclipse.buildship.core.prefs
  ci/cloud/eck/build.gradle
Labels: backport

#594 [7.8] Fix print info, certifcate issue (#591)
  ci/cloud/ece/build.gradle
  ci/cloud/eck/build.gradle
Labels: backport

#595 [7.7] Fix print info, certifcate issue (#591)
  ci/cloud/ece/build.gradle
  ci/cloud/eck/build.gradle
Labels: backport

#596 [6.8] Fix print info, certifcate issue (#591)
  ci/cloud/ece/build.gradle
  ci/cloud/eck/build.gradle
Labels: backport
