Repository elastic/elastic-stack-testing, pull requests merged in 2020-11, with the labels that each got.

#704 Re-balance xpack CI groups
  ci/kibana/group_defs.sh
Labels: :CI:Jobs

#711 [7.x] Add kibana settings for maps and reporting (#710)
  ci/cloud/product/settings/kibana.yml
Labels: backport

#712 [7.10] Add kibana settings for maps and reporting (#710)
  ci/cloud/product/settings/kibana.yml
Labels: backport

#714 Update upgrade paths and some bug fixes
  ci/cloud/buildSrc/src/main/java/org/estf/gradle/CreateCloudCluster.java
  ci/cloud/saas/build.gradle
  ci/cloud/saas/upgrade_paths.json
Labels: :Cloud Framework
