Repository elastic/elastic-stack-testing, pull requests merged in 2021-01, with the labels that each got.

#745 Workaround for version not working anymore
  ci/cloud/ece/build.gradle
  ci/cloud/ece/ecePlan.json
Labels: :Cloud Framework

#751 Revert to using node type defaults
  ci/upgrade/buildSrc/src/main/java/org/estf/gradle/CreateEssDeployment.java
Labels: :Cloud Framework

#757 [7.10] Remove OSS from testing (#754)
  ci/kibana/docker/basic/docker-compose.yml
  ci/kibana/group_defs.sh
  ci/kibana/jenkins_kibana_tests.sh
  ci/kibana/jobs/cloud_jobs.yml
  ci/kibana/jobs/darwin_jobs.yml
  ci/kibana/jobs/docker_jobs.yml
  ci/kibana/jobs/ece_jobs.yml
  ci/kibana/jobs/eck_jobs.yml
  ci/kibana/jobs/linux_arm_jobs.yml
  ci/kibana/jobs/linux_jobs.yml
  ci/kibana/jobs/windows_jobs.yml
  ci/kibana/settings/basic/kibana.yml
Labels: backport

#756 [7.11] Remove OSS from testing (#754)
  ci/kibana/docker/basic/docker-compose.yml
  ci/kibana/group_defs.sh
  ci/kibana/jenkins_kibana_tests.sh
  ci/kibana/jobs/cloud_jobs.yml
  ci/kibana/jobs/darwin_jobs.yml
  ci/kibana/jobs/docker_jobs.yml
  ci/kibana/jobs/ece_jobs.yml
  ci/kibana/jobs/eck_jobs.yml
  ci/kibana/jobs/linux_arm_jobs.yml
  ci/kibana/jobs/linux_jobs.yml
  ci/kibana/jobs/windows_jobs.yml
  ci/kibana/settings/basic/kibana.yml
Labels: backport

#760 Update elasticsearch certs
  ci/kibana/docker/default/create-certs.yml
  ci/kibana/jenkins_kibana_tests.sh
Labels: :Kibana Framework, v8.0.0

#761 [7.x] Remove intake jobs (#759)
  ci/kibana/jobs/darwin_jobs.yml
  ci/kibana/jobs/linux_jobs.yml
Labels: backport

#762 [7.11] Remove intake jobs (#759)
  ci/kibana/jobs/darwin_jobs.yml
  ci/kibana/jobs/linux_jobs.yml
Labels: backport

#763 [7.10] Remove intake jobs (#759)
  ci/kibana/jobs/darwin_jobs.yml
  ci/kibana/jobs/linux_jobs.yml
Labels: backport

#764 [6.8] Remove intake jobs (#759)
  ci/kibana/jobs/darwin_jobs.yml
  ci/kibana/jobs/linux_jobs.yml
Labels: backport

#765 Fix visual tests
  ci/kibana/jenkins_kibana_tests.sh
Labels: :Visual Testing Framework

#766 [7.x] Fix visual tests (#765)
  ci/kibana/jenkins_kibana_tests.sh
Labels: backport

#767 [7.11] Fix visual tests (#765)
  ci/kibana/jenkins_kibana_tests.sh
Labels: backport

#768 [7.x] Add cloud Kibana setting for search session tests (#753)
  ci/cloud/product/settings/kibana.yml
Labels: backport

#769 [7.11] Add cloud Kibana setting for search session tests (#753)
  ci/cloud/product/settings/kibana.yml
Labels: backport

#774 [6.8] Remove oss testing (#770)
  playbooks/stack_testing/ci/jenkins_stack_testing.sh
Labels: backport

#773 [7.10] Remove oss testing (#770)
  playbooks/stack_testing/ci/jenkins_stack_testing.sh
Labels: backport

#772 [7.11] Remove oss testing (#770)
  playbooks/stack_testing/ci/jenkins_stack_testing.sh
Labels: backport

#771 [7.x] Remove oss testing (#770)
  playbooks/stack_testing/ci/jenkins_stack_testing.sh
Labels: backport

#779 [7.10] Fix build type (#776)
  playbooks/stack_testing/ci/jenkins_stack_testing.sh
Labels: backport

#780 [6.8] Fix build type (#776)
  playbooks/stack_testing/ci/jenkins_stack_testing.sh
Labels: backport

#778 [7.11] Fix build type (#776)
  playbooks/stack_testing/ci/jenkins_stack_testing.sh
Labels: backport

#777 [7.x] Fix build type (#776)
  playbooks/stack_testing/ci/jenkins_stack_testing.sh
Labels: backport

#782 [7.x] Remove data_enhanced.search.sendToBackground setting (#781)
  ci/cloud/product/settings/kibana.yml
Labels: backport

#784 [7.x] Add back renamed setting (#783)
  ci/cloud/product/settings/kibana.yml
Labels: backport

#785 Remove non-existent tests and temporarily remove session idle timeout tests from the Cloud test suite.
  .gitignore
  ci/cloud/product/settings/kibana.yml
  ci/kibana/group_defs.sh
  ci/kibana/jenkins_kibana_tests.sh
Labels: v7.11.0, v7.12.0

#787 [7.11] Remove non-existent tests and temporarily remove session idle timeout tests from the Cloud test suite. (#785)
  .gitignore
  ci/cloud/product/settings/kibana.yml
  ci/kibana/group_defs.sh
  ci/kibana/jenkins_kibana_tests.sh
Labels: backport

#786 [7.x] Remove non-existent tests and temporarily remove session idle timeout tests from the Cloud test suite. (#785)
  .gitignore
  ci/cloud/product/settings/kibana.yml
  ci/kibana/group_defs.sh
  ci/kibana/jenkins_kibana_tests.sh
Labels: backport
